version: '2'

services:

  build:
    build:
      context: .
    image: beachfront:alg-ndwi

  bash:
    image: beachfront:alg-ndwi
    entrypoint: /bin/bash
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
    volumes:
      - '.:/work:rw'

  test:
    image: beachfront:alg-ndwi
    command: bash -c 'nosetests -v -s --with-coverage --cover-inclusive --cover-package bfalg_ndwi'
    working_dir: /work
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib
    volumes:
      - '.:/work:rw'

  package:
    image: beachfront:alg-ndwi
    working_dir: /work
    command: bash -c 'cd deploy; ./package-cf.sh'
    volumes:
      - '.:/work:rw'

  testpackage:
    build:
      context: .
      dockerfile: Dockerfile-test
    image: beachfront:alg-ndwi-test
    working_dir: /work
    command: bash -c 'nosetests -v -s;'
    volumes:
      - './deploy:/work/deploy:rw'
      - './test:/work/test'
    environment:
      - LD_LIBRARY_PATH=/work/deploy/lib
      - PYTHONPATH=/work/deploy/lib/python2.7/dist-packages
      - GDAL_DATA=/work/deploy/share/gdal

  bashpackage:
    image: beachfront:alg-ndwi-test
    entrypoint: /bin/bash
    working_dir: /work
    volumes:
      - './deploy:/work:rw'
      - './test:/work/test'
    environment:
      - LD_LIBRARY_PATH=/work/lib
      - PYTHONPATH=/work/lib/python2.7/dist-packages
