name: bfalg-ndwi-dev
channels:
  - https://proxy:proxy@nexus.devops.geointservices.io/content/repositories/beachfront-conda
dependencies:
  - beachfront
  - numpy=1.12.0=py27_blas_openblas_200
  - nose=1.3.7
  - coverage=4.3.4

