# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more detail
version: 2


references:

  container: &container
    docker:
      - image: venicegeo/geolambda-beachfront
    working_dir: ~/project

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v0-repo-{{ .Branch }}-{{ .Revision }}
        - v0-repo-{{ .Branch }}
        - v0-repo

jobs:

  checkout_code:
    <<: *container
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
            - /usr/local

  install_and_test_27:
    <<: *container
    steps:  
      - *restore_repo
      - restore_cache:
          keys: 
            - v0-dependencies27-{{ checksum "requirements.txt"}}
            - v0-dependencies27
      - run: |
            pip install virtualenv
            virtualenv ~/venv27 --system-site-packages
            . ~/venv27/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            deactivate
            . ~/venv27/bin/activate
            nosetests -v --with-coverage --cover-package bfalg_ndwi
      - save_cache:
          key: v0-dependencies27-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv27

  install_and_test_36:
    <<: *container
    steps:  
      - *restore_repo
      - restore_cache:
          keys: 
            - v0-dependencies36-{{ checksum "requirements.txt"}}
            - v0-dependencies36
      - run: |
            pip-3.6 install --user virtualenv
            ~/.local/bin/virtualenv ~/venv36 --system-site-packages
            . ~/venv36/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            deactivate
            . ~/venv36/bin/activate
            nosetests -v --with-coverage --cover-package bfalg_ndwi
      - save_cache:
          key: v0-dependencies36-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv36

  deploy:
    <<: *container
    steps:
      - *restore_repo
      - restore_cache:
          keys: 
            - v0-dependencies36-{{ checksum "requirements.txt"}}
            - v0-dependencies36
      - run:
          name: Push tag to github
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            VERSION=`awk -F\' '{print $2,$4}' bfalg_ndwi/version.py`
            git tag $VERSION
            git push origin $VERSION

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code
      - install_and_test_36:
          requires:
            - checkout_code
      - deploy:
          requires:
            - install_and_test_36
          filters:
            branches:
              only: master
  build_test:
    jobs:
      - checkout_code
      - install_and_test_27:
          requires:
            - checkout_code
