version: '2'

services:

  build:
    build:
      context: .
      dockerfile: docker/Dockerfile-cf
    image: beachfront:alg-ndwi

  bash:
    image: beachfront:alg-ndwi
    entrypoint: /bin/bash
    volumes:
      - '.:/work/app:rw'

  test:
    image: beachfront:alg-ndwi
    command: bash -c 'nosetests -v -s;'
    working_dir: /work
    volumes:
      - '.:/work:rw'

  # run the algorithm
  alg:
    image: beachfront:alg-ndwi
    command: ['python', 'bfalg-ndwi.py']


  package:
    image: beachfront:alg-ndwi
    working_dir: /work
    command: bash -c 'cd deploy; ./package-cf.sh'
    volumes:
      - '.:/work:rw'

  testpackage:
    build:
      context: .
      dockerfile: docker/Dockerfile-cf-test
    working_dir: /work
    #command: bash -c 'cd lib/python2.7/dist-packages/test; nosetests test_ndwi -v -s;'
    command: bash -c 'python bfalg-ndwi.py';
    volumes:
      - './deploy:/work:rw'
    environment:
      - LD_LIBRARY_PATH=/work/lib
      - PYTHONPATH=/work/lib/python2.7/dist-packages
